### ISSUE TITLE
Add this overlay to the official list of overlays

### ISSUE THREAD

**Issue by stefan-langenmaier** [gentoo/eclipse-overlay#14]
https://wiki.gentoo.org/wiki/Project:Overlays/Overlays_guide

**Comment by hartwork** [comment]
We will need a mail alias. I have opened this ticket to infra now:
https://bugs.gentoo.org/show_bug.cgi?id=599648

**Comment by stefan-langenmaier** [comment]
Cool, thanks! I opened the issue because I wanted to update wiki page for eclipse: https://wiki.gentoo.org/wiki/Eclipse
It still references the java overlay, so maybe we can update the page after it's in the overlay list.

**Comment by hartwork** [comment]
Added.

@stefan-langenmaier , I have added you to the `eclipse@g.o` mail alias (but it may take up to an hour for that change to go live).

**Comment by stefan-langenmaier** [comment]
Cool!
