### ISSUE TITLE
GPL broken by Gentoo

### ISSUE THREAD

**Issue by ghost** [gentoo/eclipse-overlay#19]
There is GPL that allows **anyone** who wants it to modify Gentoo freely and have their work submitted into nearest release.

So who and why introduced PR approval? Dont tell me about QA and associated crap; if sth is edditable by anyone, there is no such thing like QA.

**Comment by timeraider4u** [comment]
@wlisik: May I suggest that you re-read GPL? You are allowed to fork software A, apply changes A* and redistribute A* source- and binaries under the GPL. There is NO obligation for the original software developer of A to integrate your changes A* into his own product. E.g., imagine that I change the ext4 filesystem of the Linux kernel which implements some feature X but introduces some security issue Y. The linux developers do not have to accept my pull requests for feature X. In fact it is quite okay for them to just reject them for any reason they want.

**Comment by timeraider4u** [comment]
GPL is a copy-left license. In fact the software developers GRANT you some rights. The rights to fork, modify and re-distribute the software (as long as you still release your fork and changes under the terms of the GPL). The original software developers may still offer a dual-license for their original product which can even be non-free.
