### ISSUE TITLE
Unable to install - emerge: there are no ebuilds to satisfy ">=dev-java/icu4j-56.1:56".

### ISSUE THREAD

**Issue by RadoslavL** [gentoo/eclipse-overlay#27]
I am unable to install eclipse-sdk-bin, because it's trying to install dev-java/icu4j-56.1:56, but that's not in the official repos.

**Comment by hartwork** [comment]
From a quick look, `dev-java/icu4j:56` was removed in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=e90cc42c61203aba198ba50917516dac4fd4f505 in context of bug https://bugs.gentoo.org/787803 .
Given that Eclipse 4.6.2 is nowhere near current today, maybe it's about time to sunset this overlay.

**Comment by RadoslavL** [comment]
I installed eclipse from their website. Thank you for the provided help!
